version: "3.3"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.9.2
    command: -H unix:///var/run/docker.sock
    restart: always
    networks:
      - proxy-net
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:

networks:
  proxy-net:
    external:
      name: npm_proxy
